version: '3.9'


services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: netology_flask


  app:
    build:
      context: .
    environment:
      PG_DSN: postgresql+asyncpg://app:1234@db:5432/netology_flask
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart:
      always
    volumes:
      - ./app:/app
    working_dir: /app     
    entrypoint: sh ./run.sh  

